-- MySQL Script generated by MySQL Workbench
-- Sun Jun 21 17:31:47 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema denuncias_trabalho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema denuncias_trabalho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `denuncias_trabalho` DEFAULT CHARACTER SET utf8 ;
USE `denuncias_trabalho` ;

-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`cidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(4) NOT NULL,
  `poligono` POLYGON NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`bairro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `poligono` POLYGON NOT NULL,
  `cidades_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cidades_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_bairro_cidades1_idx` (`cidades_id` ASC) VISIBLE,
  CONSTRAINT `fk_bairro_cidades1`
    FOREIGN KEY (`cidades_id`)
    REFERENCES `denuncias_trabalho`.`cidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`logradouro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `linha` LINESTRING NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`endereco_crime_reportado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`endereco_crime_reportado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ponto` POINT NOT NULL,
  `referencia` VARCHAR(70) NOT NULL,
  `logradouro_id` INT NOT NULL,
  `bairro_id` INT NOT NULL,
  PRIMARY KEY (`id`, `bairro_id`, `logradouro_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_endereco_crime_reportado_logradouro1_idx` (`logradouro_id` ASC) VISIBLE,
  INDEX `fk_endereco_crime_reportado_bairro1_idx` (`bairro_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_crime_reportado_logradouro1`
    FOREIGN KEY (`logradouro_id`)
    REFERENCES `denuncias_trabalho`.`logradouro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_crime_reportado_bairro1`
    FOREIGN KEY (`bairro_id`)
    REFERENCES `denuncias_trabalho`.`bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`crime_reportado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`crime_reportado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `momento_do_crime` DATETIME NOT NULL,
  `endereco_crime_reportado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_crime_reportado_endereco_crime_reportado1_idx` (`endereco_crime_reportado_id` ASC) VISIBLE,
  CONSTRAINT `fk_crime_reportado_endereco_crime_reportado1`
    FOREIGN KEY (`endereco_crime_reportado_id`)
    REFERENCES `denuncias_trabalho`.`endereco_crime_reportado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`roubo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`roubo` (
  `crime_reportado_id` INT NOT NULL,
  `bens_perdidos` INT NOT NULL,
  PRIMARY KEY (`crime_reportado_id`),
  CONSTRAINT `fk_roubo_crime_reportado1`
    FOREIGN KEY (`crime_reportado_id`)
    REFERENCES `denuncias_trabalho`.`crime_reportado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`criminosos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`criminosos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantidade_de_individuos` INT NULL,
  `descricao` VARCHAR(300) NULL,
  `crime_reportado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_criminosos_crime_reportado1_idx` (`crime_reportado_id` ASC) VISIBLE,
  CONSTRAINT `fk_criminosos_crime_reportado1`
    FOREIGN KEY (`crime_reportado_id`)
    REFERENCES `denuncias_trabalho`.`crime_reportado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `data_de_nascimento` DATE NULL,
  `cpf` VARCHAR(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`usuario` (
  `id` INT NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `status` TINYINT NOT NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_pessoa`
    FOREIGN KEY (`id`)
    REFERENCES `denuncias_trabalho`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`vitima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`vitima` (
  `id` INT NOT NULL,
  `vivo` TINYINT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_vitima_pessoa1`
    FOREIGN KEY (`id`)
    REFERENCES `denuncias_trabalho`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`crime_reportado-vitima-R2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`crime_reportado-vitima-R2` (
  `crime_reportado_id` INT NOT NULL,
  `vitima_id` INT NOT NULL,
  PRIMARY KEY (`crime_reportado_id`, `vitima_id`),
  INDEX `fk_crime_reportado_has_vitima_vitima1_idx` (`vitima_id` ASC) VISIBLE,
  INDEX `fk_crime_reportado_has_vitima_crime_reportado1_idx` (`crime_reportado_id` ASC) VISIBLE,
  CONSTRAINT `fk_crime_reportado_has_vitima_crime_reportado1`
    FOREIGN KEY (`crime_reportado_id`)
    REFERENCES `denuncias_trabalho`.`crime_reportado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crime_reportado_has_vitima_vitima1`
    FOREIGN KEY (`vitima_id`)
    REFERENCES `denuncias_trabalho`.`vitima` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`sequestro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`sequestro` (
  `crime_reportado_id` INT NOT NULL,
  `momento_liberto` DATETIME NULL,
  PRIMARY KEY (`crime_reportado_id`),
  CONSTRAINT `fk_sequestro_crime_reportado1`
    FOREIGN KEY (`crime_reportado_id`)
    REFERENCES `denuncias_trabalho`.`crime_reportado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`logradouro_has_bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`logradouro_has_bairro` (
  `logradouro_id` INT NOT NULL,
  `bairro_id` INT NOT NULL,
  PRIMARY KEY (`logradouro_id`, `bairro_id`),
  INDEX `fk_logradouro_has_bairro_bairro1_idx` (`bairro_id` ASC) VISIBLE,
  INDEX `fk_logradouro_has_bairro_logradouro1_idx` (`logradouro_id` ASC) VISIBLE,
  CONSTRAINT `fk_logradouro_has_bairro_logradouro1`
    FOREIGN KEY (`logradouro_id`)
    REFERENCES `denuncias_trabalho`.`logradouro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logradouro_has_bairro_bairro1`
    FOREIGN KEY (`bairro_id`)
    REFERENCES `denuncias_trabalho`.`bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denuncias_trabalho`.`usuario-crime_reportado-R1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncias_trabalho`.`usuario-crime_reportado-R1` (
  `crime_reportado_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `id` INT NOT NULL,
  `IP` VARCHAR(12) NOT NULL,
  `momento` DATETIME NOT NULL,
  PRIMARY KEY (`crime_reportado_id`, `usuario_id`, `id`),
  INDEX `fk_usuario-crime_reportado-R1_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario-crime_reportado-R1_crime_reportado1`
    FOREIGN KEY (`crime_reportado_id`)
    REFERENCES `denuncias_trabalho`.`crime_reportado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario-crime_reportado-R1_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `denuncias_trabalho`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
